version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.api
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    hostname: teste.dev.teste
    depends_on:
      - api_db

  api_db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: api_product_main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33093:3306